dist: trusty
sudo: required

env:
  TRAVIS_DOCKER_COMPOSE_VERSION: 1.12.0
  TRAVIS_NODE_VERSION: 4.8.1
  TRAVIS_NPM_VERSION: 4.4.4

before_install:
  - sudo apt-get update -y
  - sudo apt-get update --fix-mixing
  - npm install -g npm@${TRAVIS_NPM_VERSION}
  - sudo curl -fsSL https://get.docker.com/ | sh
  - if [ -e /usr/local/bin/docker-compose ]; then sudo rm /usr/local/bin/docker-compose; fi
  - sudo curl -L https://github.com/docker/compose/releases/download/${TRAVIS_DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo docker-compose build --no-cache --force-rm
  - sudo docker-compose up -d wekandb
  - sudo docker-compose up -d wekan
  # ^^ Note - need to come up with some way of checking the output from docker run
  # that it was a success... perhaps the nodejs server can output a success message?

language: node_js

node_js:
  - "${TRAVIS_NODE_VERSION}"

install:
  - "npm install -g"

script:
  - "npm test"
