version: '2'

services:

  wekandb:
    image: mongo:3.2.20
    container_name: wekan-db
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    image: quay.io/wekan/wekan
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
        - METEOR_RELEASE=${METEOR_RELEASE}
        - NPM_VERSION=${NPM_VERSION}
        - ARCHITECTURE=${ARCHITECTURE}
        - SRC_PATH=${SRC_PATH}
        - METEOR_EDGE=${METEOR_EDGE}
        - USE_EDGE=${USE_EDGE}
    ports:
      - 80:8080
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://localhost
      # Wekan Export Board works when WITH_API='true'.
      # If you disable Wekan API with 'false', Export Board does not work.
      - WITH_API=true
      # Optional: Integration with Matomo https://matomo.org that is installed to your server
      # The address of the server where Matomo is hosted:
      # - MATOMO_ADDRESS='https://example.com/matomo'
      # The value of the site ID given in Matomo server for Wekan
      # - MATOMO_SITE_ID='123456789'
      # The option do not track which enables users to not be tracked by matomo"
      # - MATOMO_DO_NOT_TRACK='false'
      # The option that allows matomo to retrieve the username:
      # - MATOMO_WITH_USERNAME='true'
    depends_on:
      - wekandb

volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-tier:
    driver: bridge
